CREATE TABLE [CQC].[active_locations] (
    [month]                                                                                                                       INT            NULL,
    [location_id]                                                                                                                 NVARCHAR (MAX) NULL,
    [location_hsca_start_date]                                                                                                    DATE           NULL,
    [dormant]                                                                                                                     INT            NOT NULL,
    [care_home]                                                                                                                   INT            NOT NULL,
    [location_name]                                                                                                               NVARCHAR (MAX) NULL,
    [location_ods_code]                                                                                                           NVARCHAR (MAX) NULL,
    [location_telephone_number]                                                                                                   NVARCHAR (MAX) NULL,
    [location_web_address]                                                                                                        NVARCHAR (MAX) NULL,
    [care_homes_beds]                                                                                                             INT            NULL,
    [location_type_sector]                                                                                                        NVARCHAR (MAX) NULL,
    [location_inspection_directorate]                                                                                             NVARCHAR (MAX) NULL,
    [location_primary_inspection_category]                                                                                        NVARCHAR (MAX) NULL,
    [location_latest_overall_rating]                                                                                              NVARCHAR (MAX) NULL,
    [publication_date]                                                                                                            DATE           NULL,
    [inherited_rating]                                                                                                            INT            NOT NULL,
    [location_region]                                                                                                             NVARCHAR (MAX) NULL,
    [location_nhs_region]                                                                                                         NVARCHAR (MAX) NULL,
    [location_local_authority]                                                                                                    NVARCHAR (MAX) NULL,
    [location_onspd_ccg_code]                                                                                                     NVARCHAR (MAX) NULL,
    [location_onspd_ccg]                                                                                                          NVARCHAR (MAX) NULL,
    [location_commissioning_ccg_code]                                                                                             NVARCHAR (MAX) NULL,
    [location_commissioning_ccg]                                                                                                  NVARCHAR (MAX) NULL,
    [location_street_address]                                                                                                     NVARCHAR (MAX) NULL,
    [location_address_line_2]                                                                                                     NVARCHAR (MAX) NULL,
    [location_city]                                                                                                               NVARCHAR (MAX) NULL,
    [location_county]                                                                                                             NVARCHAR (MAX) NULL,
    [location_postal_code]                                                                                                        NVARCHAR (MAX) NULL,
    [location_paf_id]                                                                                                             BIGINT         NULL,
    [location_uprn_id]                                                                                                            BIGINT         NULL,
    [location_latitude]                                                                                                           FLOAT (53)     NULL,
    [location_longitude]                                                                                                          FLOAT (53)     NULL,
    [location_parliamentary_constituency]                                                                                         NVARCHAR (MAX) NULL,
    [brand_id]                                                                                                                    NVARCHAR (MAX) NULL,
    [brand_name]                                                                                                                  NVARCHAR (MAX) NULL,
    [provider_companies_house_number]                                                                                             BIGINT         NULL,
    [provider_charity_number]                                                                                                     BIGINT         NULL,
    [provider_id]                                                                                                                 NVARCHAR (MAX) NULL,
    [provider_name]                                                                                                               NVARCHAR (MAX) NULL,
    [provider_hsca_start_date]                                                                                                    DATE           NULL,
    [provider_type_sector]                                                                                                        NVARCHAR (MAX) NULL,
    [provider_inspection_directorate]                                                                                             NVARCHAR (MAX) NULL,
    [provider_primary_inspection_category]                                                                                        NVARCHAR (MAX) NULL,
    [provider_ownership_type]                                                                                                     NVARCHAR (MAX) NULL,
    [provider_telephone_number]                                                                                                   BIGINT         NULL,
    [provider_web_address]                                                                                                        NVARCHAR (MAX) NULL,
    [provider_street_address]                                                                                                     NVARCHAR (MAX) NULL,
    [provider_address_line_2]                                                                                                     NVARCHAR (MAX) NULL,
    [provider_city]                                                                                                               NVARCHAR (MAX) NULL,
    [provider_county]                                                                                                             NVARCHAR (MAX) NULL,
    [provider_postal_code]                                                                                                        NVARCHAR (MAX) NULL,
    [provider_paf_id]                                                                                                             BIGINT         NULL,
    [provider_uprn_id]                                                                                                            BIGINT         NULL,
    [provider_local_authority]                                                                                                    NVARCHAR (MAX) NULL,
    [provider_region]                                                                                                             NVARCHAR (MAX) NULL,
    [provider_nhs_region]                                                                                                         NVARCHAR (MAX) NULL,
    [provider_latitude]                                                                                                           FLOAT (53)     NULL,
    [provider_longitude]                                                                                                          FLOAT (53)     NULL,
    [provider_parliamentary_constituency]                                                                                         NVARCHAR (MAX) NULL,
    [provider_nominated_individual_name]                                                                                          NVARCHAR (MAX) NULL,
    [regulated_activity_accommodation_for_persons_who_require_nursing_or_personal_care]                                           INT            NOT NULL,
    [regulated_activity_accommodation_for_persons_who_require_treatment_for_substance_misuse]                                     INT            NOT NULL,
    [regulated_activity_assessment_or_medical_treatment_for_persons_detained_under_the_mental_health_act_1983]                    INT            NOT NULL,
    [regulated_activity_diagnostic_and_screening_procedures]                                                                      INT            NOT NULL,
    [regulated_activity_family_planning]                                                                                          INT            NOT NULL,
    [regulated_activity_management_of_supply_of_blood_and_blood_derived_products]                                                 INT            NOT NULL,
    [regulated_activity_maternity_and_midwifery_services]                                                                         INT            NOT NULL,
    [regulated_activity_nursing_care]                                                                                             INT            NOT NULL,
    [regulated_activity_personal_care]                                                                                            INT            NOT NULL,
    [regulated_activity_services_in_slimming_clinics]                                                                             INT            NOT NULL,
    [regulated_activity_surgical_procedures]                                                                                      INT            NOT NULL,
    [regulated_activity_termination_of_pregnancies]                                                                               INT            NOT NULL,
    [regulated_activity_transport_services_triage_and_medical_advice_provided_remotely]                                           INT            NOT NULL,
    [regulated_activity_treatment_of_disease_disorder_or_injury]                                                                  INT            NOT NULL,
    [service_type_acute_services_with_overnight_beds]                                                                             INT            NOT NULL,
    [service_type_acute_services_without_overnight_beds]                                                                          INT            NOT NULL,
    [service_type_ambulance_service]                                                                                              INT            NOT NULL,
    [service_type_blood_and_transplant_service]                                                                                   INT            NOT NULL,
    [service_type_care_home_service_with_nursing]                                                                                 INT            NOT NULL,
    [service_type_care_home_service_without_nursing]                                                                              INT            NOT NULL,
    [service_type_community_based_services_for_people_who_misuse_substances]                                                      INT            NOT NULL,
    [service_type_community_based_services_for_people_with_a_learning_disability]                                                 INT            NOT NULL,
    [service_type_community_based_services_for_people_with_mental_health_needs]                                                   INT            NOT NULL,
    [service_type_community_health_care_services_nurses_agency_only]                                                              INT            NOT NULL,
    [service_type_community_healthcare_service]                                                                                   INT            NOT NULL,
    [service_type_dental_service]                                                                                                 INT            NOT NULL,
    [service_type_diagnostic_and_or_screening_service]                                                                            INT            NOT NULL,
    [service_type_diagnostic_and_or_screening_service_single_handed_sessional_providers]                                          INT            NOT NULL,
    [service_type_doctors_consultation_service]                                                                                   INT            NOT NULL,
    [service_type_doctors_treatment_service]                                                                                      INT            NOT NULL,
    [service_type_domiciliary_care_service]                                                                                       INT            NOT NULL,
    [service_type_extra_care_housing_services]                                                                                    INT            NOT NULL,
    [service_type_hospice_services]                                                                                               INT            NOT NULL,
    [service_type_hospice_services_at_home]                                                                                       INT            NOT NULL,
    [service_type_hospital_services_for_people_with_mental_health_needs_learning_disabilities_and_problems_with_substance_misuse] INT            NOT NULL,
    [service_type_hyperbaric_chamber]                                                                                             INT            NOT NULL,
    [service_type_long_term_conditions_services]                                                                                  INT            NOT NULL,
    [service_type_mobile_doctors_service]                                                                                         INT            NOT NULL,
    [service_type_prison_healthcare_services]                                                                                     INT            NOT NULL,
    [service_type_rehabilitation_services]                                                                                        INT            NOT NULL,
    [service_type_remote_clinical_advice_service]                                                                                 INT            NOT NULL,
    [service_type_residential_substance_misuse_treatment_and_or_rehabilitation_service]                                           INT            NOT NULL,
    [service_type_shared_lives]                                                                                                   INT            NOT NULL,
    [service_type_specialist_college_service]                                                                                     INT            NOT NULL,
    [service_type_supported_living_service]                                                                                       INT            NOT NULL,
    [service_type_urgent_care_services]                                                                                           INT            NOT NULL,
    [service_user_band_children_0_18_years]                                                                                       INT            NOT NULL,
    [service_user_band_dementia]                                                                                                  INT            NOT NULL,
    [service_user_band_learning_disabilities_or_autistic_spectrum_disorder]                                                       INT            NOT NULL,
    [service_user_band_mental_health]                                                                                             INT            NOT NULL,
    [service_user_band_older_people]                                                                                              INT            NOT NULL,
    [service_user_band_people_detained_under_the_mental_health_act]                                                               INT            NOT NULL,
    [service_user_band_people_who_misuse_drugs_and_alcohol]                                                                       INT            NOT NULL,
    [service_user_band_people_with_an_eating_disorder]                                                                            INT            NOT NULL,
    [service_user_band_physical_disability]                                                                                       INT            NOT NULL,
    [service_user_band_sensory_impairment]                                                                                        INT            NOT NULL,
    [service_user_band_whole_population]                                                                                          INT            NOT NULL,
    [service_user_band_younger_adults]                                                                                            INT            NOT NULL
);
GO

