CREATE PROCEDURE [CQC].[p_active_locations_staging_to_final]
AS
BEGIN

DROP TABLE IF EXISTS [CQC].[active_locations];

SELECT
    CAST(REPLACE(FileName, '.csv', '') AS INT) AS month,
    [Location ID] AS location_id,
    TRY_CAST([Location HSCA start date] AS DATE) AS location_hsca_start_date,
    CASE WHEN [Dormant (Y/N)] = 'Y' THEN 1 ELSE 0 END AS dormant,
    CASE WHEN [Care home?] = 'Y' THEN 1 ELSE 0 END AS care_home,
    [Location Name] AS location_name,
    [Location ODS Code] AS location_ods_code,
    [Location Telephone Number] AS location_telephone_number,
    --[Registered manager] AS registered_manager,
    [Location Web Address] AS location_web_address,
    TRY_CAST([Care homes beds] AS INT) AS care_homes_beds,
    [Location Type/Sector] AS location_type_sector,
    [Location Inspection Directorate] AS location_inspection_directorate,
    [Location Primary Inspection Category] AS location_primary_inspection_category,
    [Location Latest Overall Rating] AS location_latest_overall_rating,
    TRY_CAST([Publication Date] AS DATE) AS publication_date,
    CASE WHEN [Inherited Rating (Y/N)] = 'Y' THEN 1 ELSE 0 END AS inherited_rating,
    [Location Region] AS location_region,
    [Location NHS Region] AS location_nhs_region,
    [Location Local Authority] AS location_local_authority,
    [Location ONSPD CCG Code] AS location_onspd_ccg_code,
    [Location ONSPD CCG] AS location_onspd_ccg,
    [Location Commissioning CCG Code] AS location_commissioning_ccg_code,
    [Location Commissioning CCG] AS location_commissioning_ccg,
    [Location Street Address] AS location_street_address,
    [Location Address Line 2] AS location_address_line_2,
    [Location City] AS location_city,
    [Location County] AS location_county,
    [Location Postal Code] AS location_postal_code,
    TRY_CAST([Location PAF ID] AS BIGINT) AS location_paf_id,
    TRY_CAST([Location UPRN ID] AS BIGINT) AS location_uprn_id,
    TRY_CAST([Location Latitude] AS FLOAT) AS location_latitude,
    TRY_CAST([Location Longitude] AS FLOAT) AS location_longitude,
    [Location Parliamentary Constituency] AS location_parliamentary_constituency,
    [Brand ID] AS brand_id,
    [Brand Name] AS brand_name,
    TRY_CAST([Provider Companies House Number] AS BIGINT) AS provider_companies_house_number,
    TRY_CAST([Provider Charity Number] AS BIGINT) AS provider_charity_number,
    [Provider ID] AS provider_id,
    [Provider Name] AS provider_name,
    TRY_CAST([Provider HSCA start date] AS DATE) AS provider_hsca_start_date,
    [Provider Type/Sector] AS provider_type_sector,
    [Provider Inspection Directorate] AS provider_inspection_directorate,
    [Provider Primary Inspection Category] AS provider_primary_inspection_category,
    [Provider Ownership Type] AS provider_ownership_type,
    TRY_CAST([Provider Telephone Number] AS BIGINT) AS provider_telephone_number,
    [Provider Web Address] AS provider_web_address,
    [Provider Street Address] AS provider_street_address,
    [Provider Address Line 2] AS provider_address_line_2,
    [Provider City] AS provider_city,
    [Provider County] AS provider_county,
    [Provider Postal Code] AS provider_postal_code,
    TRY_CAST([Provider PAF ID] AS BIGINT) AS provider_paf_id,
    TRY_CAST([Provider UPRN ID] AS BIGINT) AS provider_uprn_id,
    [Provider Local Authority] AS provider_local_authority,
    [Provider Region] AS provider_region,
    [Provider NHS Region] AS provider_nhs_region,
    TRY_CAST([Provider Latitude] AS FLOAT) AS provider_latitude,
    TRY_CAST([Provider Longitude] AS FLOAT) AS provider_longitude,
    [Provider Parliamentary Constituency] AS provider_parliamentary_constituency,
    [Provider Nominated Individual Name] AS provider_nominated_individual_name,
    --[Provider Main Partner Name] AS provider_main_partner_name,
    CASE WHEN [Regulated activity - Accommodation for persons who require nursing or personal care] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_accommodation_for_persons_who_require_nursing_or_personal_care,
    CASE WHEN [Regulated activity - Accommodation for persons who require treatment for substance misuse] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_accommodation_for_persons_who_require_treatment_for_substance_misuse,
    CASE WHEN [Regulated activity - Assessment or medical treatment for persons detained under the Mental Health Act 1983] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_assessment_or_medical_treatment_for_persons_detained_under_the_mental_health_act_1983,
    CASE WHEN [Regulated activity - Diagnostic and screening procedures] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_diagnostic_and_screening_procedures,
    CASE WHEN [Regulated activity - Family planning] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_family_planning,
    CASE WHEN [Regulated activity - Management of supply of blood and blood derived products] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_management_of_supply_of_blood_and_blood_derived_products,
    CASE WHEN [Regulated activity - Maternity and midwifery services] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_maternity_and_midwifery_services,
    CASE WHEN [Regulated activity - Nursing care] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_nursing_care,
    CASE WHEN [Regulated activity - Personal care] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_personal_care,
    CASE WHEN [Regulated activity - Services in slimming clinics] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_services_in_slimming_clinics,
    CASE WHEN [Regulated activity - Surgical procedures] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_surgical_procedures,
    CASE WHEN [Regulated activity - Termination of pregnancies] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_termination_of_pregnancies,
    CASE WHEN [Regulated activity - Transport services, triage and medical advice provided remotely] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_transport_services_triage_and_medical_advice_provided_remotely,
    CASE WHEN [Regulated activity - Treatment of disease, disorder or injury] = 'Y' THEN 1 ELSE 0 END AS regulated_activity_treatment_of_disease_disorder_or_injury,
    CASE WHEN [Service type - Acute services with overnight beds] = 'Y' THEN 1 ELSE 0 END AS service_type_acute_services_with_overnight_beds,
    CASE WHEN [Service type - Acute services without overnight beds / listed acute services with or without overnight beds] = 'Y' THEN 1 ELSE 0 END AS service_type_acute_services_without_overnight_beds,
    CASE WHEN [Service type - Ambulance service] = 'Y' THEN 1 ELSE 0 END AS service_type_ambulance_service,
    CASE WHEN [Service type - Blood and Transplant service] = 'Y' THEN 1 ELSE 0 END AS service_type_blood_and_transplant_service,
    CASE WHEN [Service type - Care home service with nursing] = 'Y' THEN 1 ELSE 0 END AS service_type_care_home_service_with_nursing,
    CASE WHEN [Service type - Care home service without nursing] = 'Y' THEN 1 ELSE 0 END AS service_type_care_home_service_without_nursing,
    CASE WHEN [Service type - Community based services for people who misuse substances] = 'Y' THEN 1 ELSE 0 END AS service_type_community_based_services_for_people_who_misuse_substances,
    CASE WHEN [Service type - Community based services for people with a learning disability] = 'Y' THEN 1 ELSE 0 END AS service_type_community_based_services_for_people_with_a_learning_disability,
    CASE WHEN [Service type - Community based services for people with mental health needs] = 'Y' THEN 1 ELSE 0 END AS service_type_community_based_services_for_people_with_mental_health_needs,
    CASE WHEN [Service type - Community health care services - Nurses Agency only] = 'Y' THEN 1 ELSE 0 END AS service_type_community_health_care_services_nurses_agency_only,
    CASE WHEN [Service type - Community healthcare service] = 'Y' THEN 1 ELSE 0 END AS service_type_community_healthcare_service,
    CASE WHEN [Service type - Dental service] = 'Y' THEN 1 ELSE 0 END AS service_type_dental_service,
    CASE WHEN [Service type - Diagnostic and/or screening service] = 'Y' THEN 1 ELSE 0 END AS service_type_diagnostic_and_or_screening_service,
    CASE WHEN [Service type - Diagnostic and/or screening service - single handed sessional providers] = 'Y' THEN 1 ELSE 0 END AS service_type_diagnostic_and_or_screening_service_single_handed_sessional_providers,
    CASE WHEN [Service type - Doctors consultation service] = 'Y' THEN 1 ELSE 0 END AS service_type_doctors_consultation_service,
    CASE WHEN [Service type - Doctors treatment service] = 'Y' THEN 1 ELSE 0 END AS service_type_doctors_treatment_service,
    CASE WHEN [Service type - Domiciliary care service] = 'Y' THEN 1 ELSE 0 END AS service_type_domiciliary_care_service,
    CASE WHEN [Service type - Extra Care housing services] = 'Y' THEN 1 ELSE 0 END AS service_type_extra_care_housing_services,
    CASE WHEN [Service type - Hospice services] = 'Y' THEN 1 ELSE 0 END AS service_type_hospice_services,
    CASE WHEN [Service type - Hospice services at home] = 'Y' THEN 1 ELSE 0 END AS service_type_hospice_services_at_home,
    CASE WHEN [Service type - Hospital services for people with mental health needs, learning disabilities and problems with substance misuse] = 'Y' THEN 1 ELSE 0 END AS service_type_hospital_services_for_people_with_mental_health_needs_learning_disabilities_and_problems_with_substance_misuse,
    CASE WHEN [Service type - Hyperbaric Chamber] = 'Y' THEN 1 ELSE 0 END AS service_type_hyperbaric_chamber,
    CASE WHEN [Service type - Long term conditions services] = 'Y' THEN 1 ELSE 0 END AS service_type_long_term_conditions_services,
    CASE WHEN [Service type - Mobile doctors service] = 'Y' THEN 1 ELSE 0 END AS service_type_mobile_doctors_service,
    CASE WHEN [Service type - Prison Healthcare Services] = 'Y' THEN 1 ELSE 0 END AS service_type_prison_healthcare_services,
    CASE WHEN [Service type - Rehabilitation services] = 'Y' THEN 1 ELSE 0 END AS service_type_rehabilitation_services,
    CASE WHEN [Service type - Remote clinical advice service] = 'Y' THEN 1 ELSE 0 END AS service_type_remote_clinical_advice_service,
    CASE WHEN [Service type - Residential substance misuse treatment and/or rehabilitation service] = 'Y' THEN 1 ELSE 0 END AS service_type_residential_substance_misuse_treatment_and_or_rehabilitation_service,
    CASE WHEN [Service type - Shared Lives] = 'Y' THEN 1 ELSE 0 END AS service_type_shared_lives,
    CASE WHEN [Service type - Specialist college service] = 'Y' THEN 1 ELSE 0 END AS service_type_specialist_college_service,
    CASE WHEN [Service type - Supported living service] = 'Y' THEN 1 ELSE 0 END AS service_type_supported_living_service,
    CASE WHEN [Service type - Urgent care services] = 'Y' THEN 1 ELSE 0 END AS service_type_urgent_care_services,
    CASE WHEN [Service user band - Children 0-18 years] = 'Y' THEN 1 ELSE 0 END AS service_user_band_children_0_18_years,
    CASE WHEN [Service user band - Dementia] = 'Y' THEN 1 ELSE 0 END AS service_user_band_dementia,
    CASE WHEN [Service user band - Learning disabilities or autistic spectrum disorder] = 'Y' THEN 1 ELSE 0 END AS service_user_band_learning_disabilities_or_autistic_spectrum_disorder,
    CASE WHEN [Service user band - Mental Health] = 'Y' THEN 1 ELSE 0 END AS service_user_band_mental_health,
    CASE WHEN [Service user band - Older People] = 'Y' THEN 1 ELSE 0 END AS service_user_band_older_people,
    CASE WHEN [Service user band - People detained under the Mental Health Act] = 'Y' THEN 1 ELSE 0 END AS service_user_band_people_detained_under_the_mental_health_act,
    CASE WHEN [Service user band - People who misuse drugs and alcohol] = 'Y' THEN 1 ELSE 0 END AS service_user_band_people_who_misuse_drugs_and_alcohol,
    CASE WHEN [Service user band - People with an eating disorder] = 'Y' THEN 1 ELSE 0 END AS service_user_band_people_with_an_eating_disorder,
    CASE WHEN [Service user band - Physical Disability] = 'Y' THEN 1 ELSE 0 END AS service_user_band_physical_disability,
    CASE WHEN [Service user band - Sensory Impairment] = 'Y' THEN 1 ELSE 0 END AS service_user_band_sensory_impairment,
    CASE WHEN [Service user band - Whole Population] = 'Y' THEN 1 ELSE 0 END AS service_user_band_whole_population,
    CASE WHEN [Service user band - Younger Adults] = 'Y' THEN 1 ELSE 0 END AS service_user_band_younger_adults
    INTO [CQC].[active_locations]
    FROM [CQC].[active_locations_staging];

DROP TABLE IF EXISTS [CQC].[active_locations_staging];

END;
GO

